# Rewrite the main renderQuiz() body in src/ui/quiz-view.js for v1.15.0.
# Only the post-sudden-death main path (line ~292 onward) is replaced.
# Sudden Death rendering, helper functions, and initQuizEvents are preserved.
# Idempotent: rerunning replaces between BEGIN and END markers.
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
target = ROOT / "src/ui/quiz-view.js"
src = target.read_text(encoding="utf-8")

START_ANCHOR = "if(!G.pool.length)buildPool();\nif(G.qi>=G.pool.length)G.qi=0;\n"
start = src.find(START_ANCHOR)
if start == -1:
    raise SystemExit("ERROR: start anchor not found.")
END_MARKER = "\n// Sudden Death check/next\n"
end_idx = src.find(END_MARKER, start)
if end_idx == -1:
    raise SystemExit("ERROR: end marker not found.")
slice_to_replace = src[start:end_idx]
if not slice_to_replace.endswith("return h;\n}"):
    raise SystemExit(f"ERROR: tail unexpected:\n{slice_to_replace[-200:]!r}")

new_body = (
    "// === MAIN QUIZ PATH (v1.15.0 rebuild — Editorial Clinical) ===\n"
    "// Emits semantic, class-driven HTML against src/ui/quiz-view.css.\n"
    "// ZERO inline `style=\"\"` attributes. All dimensions/colors via CSS tokens.\n"
    "// Preserves every data-action name from the previous implementation —\n"
    "// event delegation in initQuizEvents() (below) keeps working unchanged.\n"
    "if(!G.pool.length)buildPool();\n"
    "if(G.qi>=G.pool.length)G.qi=0;\n"
    "const q=G.QZ[G.pool[G.qi]];\n"
    "const tot=G.S.qOk+G.S.qNo;\n"
    "const pct=tot?Math.round(G.S.qOk/tot*100)+'%':'—';\n"
    "const bk=G.S.bk[G.pool[G.qi]];\n"
    "const dueN=getDueQuestions().length;\n"
    "\n"
    "let h='<section class=\"quiz-stage\" aria-label=\"Question\">';\n"
    "\n"
    "// ── Pomodoro banner ─────────────────────────────────────────────────\n"
    "if(G.pomoActive){\n"
    "  h+=`<div class=\"quiz-banner quiz-banner--pomo\">`+\n"
    "     `<span class=\"quiz-banner__label\">Pomodoro</span>`+\n"
    "     `<span class=\"quiz-banner__timer\" id=\"pomo-time\">${fmtT(G.pomoSec)}</span>`+\n"
    "     `<button class=\"btn btn--ghost\" data-action=\"stop-pomo\" aria-label=\"Stop pomodoro timer\">Stop</button>`+\n"
    "     `</div>`;\n"
    "}\n"
    "\n"
    "// ── Exam-mode banner ────────────────────────────────────────────────\n"
    "if(G.examMode){\n"
    "  const isMock=!!G.mockExamResults;\n"
    "  const totalQ=isMock?G.pool.length:150;\n"
    "  h+=`<div class=\"quiz-banner quiz-banner--exam\">`+\n"
    "     `<span class=\"quiz-banner__label\">${isMock?'Mock Exam':'Exam'}</span>`+\n"
    "     `<span class=\"quiz-banner__timer\" id=\"etimer\">${fmtT(G.examSec)}</span>`+\n"
    "     `<span>${G.qi+1} / ${totalQ}</span>`+\n"
    "     `</div>`;\n"
    "}\n"
    "\n"
    "// ── Daily Contract + filter controls (skipped under exam mode) ──────\n"
    "if(!G.examMode){\n"
    "  h+=renderDailyContract(dueN);\n"
    "  h+=renderQuizControls(dueN);\n"
    "}\n"
    "\n"
    "// ── Empty-pool guard ─────────────────────────────────────────────────\n"
    "if(!G.pool.length){\n"
    "  const msg=G.filt==='due'?'No questions due for review.'\n"
    "    :G.filt==='wrong-review'?'No wrong answers to review — your set is empty.'\n"
    "    :'No questions match this filter.';\n"
    "  h+=`<div class=\"quiz-empty\"><p class=\"quiz-empty__title\">All caught up</p><p>${msg}</p></div>`;\n"
    "  h+='</section>';\n"
    "  return h;\n"
    "}\n"
    "\n"
    "// ── Progress sliver ─────────────────────────────────────────────────\n"
    "h+=`<div class=\"quiz-progress\" role=\"progressbar\" aria-valuenow=\"${G.qi+1}\" aria-valuemin=\"1\" aria-valuemax=\"${G.pool.length}\">`+\n"
    "   `<span class=\"quiz-progress__fill\" data-progress=\"${Math.round((G.qi+1)/G.pool.length*100)}\"></span>`+\n"
    "   `</div>`;\n"
    "\n"
    "// ── Timed bar ───────────────────────────────────────────────────────\n"
    "if(G.timedMode&&!G.ans){\n"
    "  h+=`<div class=\"quiz-timed\">`+\n"
    "     `<span class=\"quiz-timed__count\" id=\"timed-count\">${G.timedSec}s</span>`+\n"
    "     `<div class=\"quiz-timed__track\"><span class=\"quiz-timed__fill\" id=\"timed-bar\" data-pct=\"${Math.round(G.timedSec/90*100)}\"></span></div>`+\n"
    "     `<button class=\"btn btn--ghost\" data-action=\"pause-timed\" aria-label=\"${G.timedPaused?'Resume timer':'Pause timer'}\">${G.timedPaused?'Resume':'Pause'}</button>`+\n"
    "     `</div>`;\n"
    "}\n"
    "\n"
    "// ── Meta row: year, topic, position, tools ──────────────────────────\n"
    "const topicName=q.ti>=0&&TOPICS[q.ti]?TOPICS[q.ti]:'';\n"
    "const tagLabel=q.t==='AI-Ch'?'AI — Chapter'\n"
    "  :q.t==='AI-Hard-G'?'Hard · Goroll'\n"
    "  :q.t==='AI-Hard-AFP'?'Hard · AFP'\n"
    "  :q.t;\n"
    "h+=`<div class=\"quiz-header\">`;\n"
    "h+=`<div class=\"quiz-meta__group\">`;\n"
    "h+=`<span class=\"pill\">${sanitize(tagLabel)}</span>`;\n"
    "if(topicName)h+=`<span class=\"pill pill--accent\">${sanitize(topicName)}</span>`;\n"
    "h+=`<span class=\"quiz-meta__counter\">${G.qi+1} / ${G.pool.length}</span>`;\n"
    "h+=`</div>`;\n"
    "h+=`<div class=\"quiz-tools\">`;\n"
    "h+=`<button class=\"quiz-tool\" data-action=\"speak-q\" title=\"Read aloud\" aria-label=\"Read question aloud\">♫</button>`;\n"
    "h+=`<button class=\"quiz-tool\" data-action=\"share-q\" id=\"shbtn\" title=\"Share\" aria-label=\"Share question\">↗</button>`;\n"
    "const hasNote=!!(G.S.qnotes&&G.S.qnotes[G.pool[G.qi]]);\n"
    "h+=`<button class=\"quiz-tool\" data-action=\"toggle-qnote\" aria-pressed=\"${hasNote}\" aria-label=\"Note\" title=\"Note\">✎</button>`;\n"
    "h+=`<button class=\"quiz-tool\" data-action=\"toggle-bk\" aria-pressed=\"${!!bk}\" aria-label=\"Bookmark\" title=\"Bookmark\">${bk?'★':'☆'}</button>`;\n"
    "h+=`</div>`;\n"
    "h+=`</div>`;\n"
    "\n"
    "// ── Question text ───────────────────────────────────────────────────\n"
    "h+=`<h2 class=\"quiz-question\" dir=\"auto\">${sanitize(q.q)}</h2>`;\n"
    "\n"
    "// ── Personal note ───────────────────────────────────────────────────\n"
    "if(hasNote){\n"
    "  h+=`<div class=\"quiz-note\" data-action=\"toggle-qnote\" dir=\"auto\" title=\"Click to edit\">${sanitize(G.S.qnotes[G.pool[G.qi]])}</div>`;\n"
    "}\n"
    "\n"
    "// ── Question image ──────────────────────────────────────────────────\n"
    "if(q.img){\n"
    "  h+=`<img class=\"quiz-image\" src=\"${sanitize(q.img)}\" alt=\"Question image\" data-action=\"view-img\" loading=\"lazy\">`;\n"
    "}\n"
    "\n"
    "// ── Answer choices (radiogroup) ─────────────────────────────────────\n"
    "const _shuf=getOptShuffle(G.pool[G.qi],q);\n"
    "const LETTERS=['A','B','C','D','E','F','G','H'];\n"
    "h+=`<ol class=\"quiz-choices\" role=\"radiogroup\" aria-label=\"Answer choices\">`;\n"
    "_shuf.forEach((origI,dispJ)=>{\n"
    "  const o=q.o[origI];\n"
    "  const isChecked=(origI===G.sel);\n"
    "  let state='';\n"
    "  if(G.ans){\n"
    "    if(!G.examMode){\n"
    "      if(isOk(q,origI)) state=isChecked?'correct':'correct-unchosen';\n"
    "      else if(isChecked) state='wrong';\n"
    "      else state='muted';\n"
    "    } else if(isChecked) state='correct';\n"
    "  }\n"
    "  const stateAttr=state?` data-state=\"${state}\"`:'';\n"
    "  const lockAttr=G.ans?' disabled':'';\n"
    "  h+=`<li><button class=\"quiz-choice\" role=\"radio\" aria-checked=\"${isChecked?'true':'false'}\"${stateAttr}${lockAttr} data-action=\"pick\" data-i=\"${origI}\" aria-label=\"Option ${LETTERS[dispJ]}: ${sanitize(o)}\">`+\n"
    "       `<span class=\"quiz-choice__letter\" aria-hidden=\"true\">${LETTERS[dispJ]}</span>`+\n"
    "       `<span class=\"quiz-choice__text\" dir=\"auto\">${sanitize(o)}</span>`+\n"
    "       `</button></li>`;\n"
    "});\n"
    "h+=`</ol>`;\n"
    "\n"
    "// ── Pre-answer footer ───────────────────────────────────────────────\n"
    "if(!G.ans){\n"
    "  h+=`<footer class=\"quiz-actions\">`;\n"
    "  h+=`<button class=\"btn btn--primary quiz-actions__primary\" data-action=\"check-answer\"${G.sel===null?' disabled':''} aria-label=\"Check answer\">Check</button>`;\n"
    "  if(!G.examMode){\n"
    "    h+=`<button class=\"btn btn--ghost\" data-action=\"give-up\" aria-label=\"Show answer\">I don't know</button>`;\n"
    "  }\n"
    "  h+=`</footer>`;\n"
    "  h+='</section>';\n"
    "  return h;\n"
    "}\n"
    "\n"
    "// ===== POST-ANSWER =====\n"
    "// ── Feedback panel ──────────────────────────────────────────────────\n"
    "const correct=isOk(q,G.sel);\n"
    "const feedbackVariant=correct?'ok':'err';\n"
    "const feedbackTitle=correct?'Correct':'Not quite';\n"
    "h+=`<aside class=\"quiz-feedback quiz-feedback--${feedbackVariant}\" role=\"status\" aria-live=\"polite\">`;\n"
    "h+=`<span class=\"quiz-feedback__title\">${feedbackTitle}</span>`;\n"
    "if(!G.examMode&&q.e){\n"
    "  const rendered=remapExplanationLetters(q.e,_shuf).replace(/\\n/g,'<br>').replace(/\\*\\*(.*?)\\*\\*/g,'<b>$1</b>');\n"
    "  h+=`<p class=\"quiz-feedback__body\" dir=\"auto\">${rendered}</p>`;\n"
    "}\n"
    "if(!G.examMode&&q.ref){\n"
    "  h+=`<div class=\"quiz-source\"><span class=\"quiz-source__label\">Source</span>${renderSourceLink(q.ref)}</div>`;\n"
    "}\n"
    "if(!G.examMode){\n"
    "  const _aiIdx=G.pool[G.qi];\n"
    "  h+=`<div class=\"quiz-feedback__row\">`;\n"
    "  if(G._exCache[_aiIdx]&&!G._exCache[_aiIdx].err){\n"
    "    h+=`<div id=\"ai-explain-${_aiIdx}\"></div>`;\n"
    "    setTimeout(()=>renderExplainBox(_aiIdx),0);\n"
    "  } else {\n"
    "    const label=G._exCache[_aiIdx]?'Retry AI explain':'Ask Claude';\n"
    "    h+=`<button class=\"btn btn--secondary\" data-action=\"ai-explain\" data-idx=\"${_aiIdx}\">${label}</button>`;\n"
    "  }\n"
    "  h+=`</div>`;\n"
    "}\n"
    "h+=`</aside>`;\n"
    "\n"
    "// ── Wrong-reason chips ──────────────────────────────────────────────\n"
    "if(!G.examMode&&!correct&&!G._wrongReason){\n"
    "  h+=`<div class=\"quiz-wrong-reason\">`+\n"
    "     `<span class=\"quiz-wrong-reason__label\">Why did you get it wrong?</span>`+\n"
    "     `<div class=\"quiz-wrong-reason__row\">`+\n"
    "     `<button class=\"btn btn--secondary\" data-action=\"wrong-reason\" data-r=\"no_knowledge\">Didn't know</button>`+\n"
    "     `<button class=\"btn btn--secondary\" data-action=\"wrong-reason\" data-r=\"misread\">Misread</button>`+\n"
    "     `<button class=\"btn btn--secondary\" data-action=\"wrong-reason\" data-r=\"between_2\">Between two</button>`+\n"
    "     `<button class=\"btn btn--secondary\" data-action=\"wrong-reason\" data-r=\"silly\">Silly</button>`+\n"
    "     `</div></div>`;\n"
    "}\n"
    "\n"
    "// ── Read-chapter shortcut ──────────────────────────────────────────\n"
    "if(!G.examMode&&!correct&&q.ti>=0){\n"
    "  const _chRef=TOPIC_REF[q.ti];\n"
    "  if(_chRef&&_chRef.s==='har'){\n"
    "    h+=`<button class=\"btn btn--secondary\" data-action=\"read-chapter\" aria-label=\"Read chapter ${sanitize(_chRef.l||'')}\">Read: ${sanitize(_chRef.l||'')}</button>`;\n"
    "  }\n"
    "}\n"
    "\n"
    "// ── Difficulty rating ──────────────────────────────────────────────\n"
    "if(!G.examMode){\n"
    "  const dr=G._diffRating;\n"
    "  h+=`<div class=\"quiz-difficulty\">`+\n"
    "     `<span class=\"quiz-difficulty__label\">Difficulty</span>`+\n"
    "     `<button class=\"btn btn--secondary\" data-action=\"diff-rating\" data-d=\"easy\" aria-pressed=\"${dr==='easy'}\">Easy</button>`+\n"
    "     `<button class=\"btn btn--secondary\" data-action=\"diff-rating\" data-d=\"med\" aria-pressed=\"${dr==='med'}\">Medium</button>`+\n"
    "     `<button class=\"btn btn--secondary\" data-action=\"diff-rating\" data-d=\"hard\" aria-pressed=\"${dr==='hard'}\">Hard</button>`+\n"
    "     `</div>`;\n"
    "}\n"
    "\n"
    "// ── Teach-back panel (correct-only) ────────────────────────────────\n"
    "if(!G.examMode&&correct){\n"
    "  if(!G.teachBackState){\n"
    "    h+=`<aside class=\"quiz-aux\">`+\n"
    "       `<span class=\"quiz-aux__title\">Teach-back</span>`+\n"
    "       `<p class=\"quiz-aux__body\">Explain why this is the right answer.</p>`+\n"
    "       `<textarea id=\"tbInput\" class=\"quiz-teachback__input\" dir=\"auto\" placeholder=\"Type your explanation…\" aria-label=\"Teach-back explanation\"></textarea>`+\n"
    "       `<div class=\"quiz-feedback__row\">`+\n"
    "       `<button class=\"btn btn--primary\" data-action=\"grade-teachback\" aria-label=\"Grade teach-back with AI\">Grade with AI</button>`+\n"
    "       `<button class=\"btn btn--ghost\" data-action=\"skip-teachback\" aria-label=\"Skip teach-back\">Skip</button>`+\n"
    "       `<button class=\"btn btn--ghost\" data-action=\"voice-teachback\" id=\"tb-mic-btn\" aria-label=\"Record voice teach-back\">Voice</button>`+\n"
    "       `</div></aside>`;\n"
    "  } else if(G.teachBackState==='grading'){\n"
    "    h+=`<aside class=\"quiz-aux\"><p class=\"quiz-aux__body\">Grading…</p></aside>`;\n"
    "  } else if(G.teachBackState!=='skip'){\n"
    "    const sc=G.teachBackState.score;\n"
    "    const scoreLabel=sc===3?'Excellent':sc===2?'Partial':'Needs work';\n"
    "    h+=`<aside class=\"quiz-aux\">`+\n"
    "       `<span class=\"quiz-aux__title\">${scoreLabel}</span>`;\n"
    "    if(G.teachBackState.feedback){\n"
    "      h+=`<p class=\"quiz-aux__body\" dir=\"auto\">${sanitize(G.teachBackState.feedback)}</p>`;\n"
    "    }\n"
    "    h+=`</aside>`;\n"
    "  }\n"
    "}\n"
    "\n"
    "// ── Distractor Autopsy ─────────────────────────────────────────────\n"
    "if(!G.examMode){\n"
    "  const _qIdx=G.pool[G.qi];\n"
    "  const _dist=(G.DIS&&G.DIS[_qIdx])||null;\n"
    "  const _apKey='autopsy_'+_qIdx;\n"
    "  const _aiTxt=G._exCache[_apKey];\n"
    "  h+=`<aside class=\"quiz-aux\"><span class=\"quiz-aux__title\">Distractor breakdown</span>`;\n"
    "  if(_dist){\n"
    "    q.o.forEach((opt,i)=>{\n"
    "      const _isCorrect=isOk(q,i);\n"
    "      const _isPick=(i===G.sel);\n"
    "      const dState=_isCorrect?'correct':(_isPick?'wrong':'');\n"
    "      const stAttr=dState?` data-state=\"${dState}\"`:'';\n"
    "      const _rationale=_dist[i];\n"
    "      const mark=_isCorrect?'✓':'✗';\n"
    "      const pickTag=(_isPick&&!_isCorrect)?' (your pick)':'';\n"
    "      h+=`<div class=\"quiz-distractor\"${stAttr} dir=\"auto\">`+\n"
    "         `<div class=\"quiz-distractor__head\">${mark} ${sanitize(opt)}${pickTag}</div>`;\n"
    "      if(_rationale){\n"
    "        const safe=sanitize(_rationale)\n"
    "          .replace(/Wrong because:/g,'<b>Wrong because:</b>')\n"
    "          .replace(/Would be correct if:/g,'<b>Would be correct if:</b>');\n"
    "        h+=`<div>${safe}</div>`;\n"
    "      } else if(_isCorrect){\n"
    "        h+=`<div>The correct answer.</div>`;\n"
    "      }\n"
    "      h+=`</div>`;\n"
    "    });\n"
    "  } else if(_aiTxt){\n"
    "    h+=`<div class=\"quiz-aux__body\" dir=\"auto\">${_aiTxt}</div>`;\n"
    "  } else {\n"
    "    h+=`<p class=\"quiz-aux__body\">Loading distractor analysis…</p>`;\n"
    "    setTimeout(()=>{ if(!G._exCache['autopsy_'+_qIdx])aiAutopsy(_qIdx); },100);\n"
    "  }\n"
    "  h+=`</aside>`;\n"
    "}\n"
    "\n"
    "// ── Stats footer ───────────────────────────────────────────────────\n"
    "h+=`<div class=\"quiz-stats\">`+\n"
    "   `<span>OK ${G.S.qOk}</span>`+\n"
    "   `<span>NO ${G.S.qNo}</span>`+\n"
    "   `<span>${pct}</span>`+\n"
    "   (G.S.sr[G.pool[G.qi]]?.at?`<span>${G.S.sr[G.pool[G.qi]].at}s avg</span>`:'')+\n"
    "   `</div>`;\n"
    "\n"
    "// ── Action footer ──────────────────────────────────────────────────\n"
    "h+=`<footer class=\"quiz-actions\">`;\n"
    "if(!G.examMode){\n"
    "  h+=`<button class=\"btn btn--secondary\" data-action=\"prev-q\" aria-label=\"Previous question\"${G.qi<=0?' disabled':''}>Previous</button>`;\n"
    "}\n"
    "h+=`<span class=\"quiz-actions__spacer\"></span>`;\n"
    "const nextLabel=G.examMode&&G.qi+1>=150?'Finish':'Next';\n"
    "const nextAria=G.examMode&&G.qi+1>=150?'Finish exam':'Next question';\n"
    "h+=`<button class=\"btn btn--primary quiz-actions__primary\" data-action=\"next-q\" aria-label=\"${nextAria}\">${nextLabel}</button>`;\n"
    "h+=`</footer>`;\n"
    "\n"
    "h+='</section>';\n"
    "return h;\n"
    "}\n"
)

new_src = src[:start] + new_body.lstrip("\n") + src[end_idx:]
target.write_text(new_src, encoding="utf-8")

HELPER_MARK = "// === renderQuizControls (v1.15.0 helper) ==="
new_src = target.read_text(encoding="utf-8")
if HELPER_MARK not in new_src:
    helper = (
        "\n" + HELPER_MARK + "\n"
        "// Filter pills + topic dropdown + mode toggles + wrong-review banner.\n"
        "// Extracted from renderQuiz so the main render path stays readable.\n"
        "// All markup uses tokenized classes; no inline styles.\n"
        "function renderQuizControls(dueN){\n"
        "  let h='<nav class=\"quiz-controls\" aria-label=\"Quiz filters\">';\n"
        "  h+='<div class=\"quiz-controls__row\">';\n"
        "  h+='<span class=\"quiz-controls__label\">Mode</span>';\n"
        "  h+='<button class=\"btn btn--secondary\" data-action=\"start-mock\" aria-label=\"Start mock exam\">Mock exam</button>';\n"
        "  h+='<button class=\"btn btn--ghost\" data-action=\"start-sd\" aria-label=\"Start sudden death\">Sudden death</button>';\n"
        "  h+='<button class=\"btn btn--ghost\" data-action=\"start-oncall\" aria-label=\"Start on-call mode\">On-call</button>';\n"
        "  if(!G.pomoActive)h+='<button class=\"btn btn--ghost\" data-action=\"start-pomo\" aria-label=\"Start pomodoro timer\">Pomodoro</button>';\n"
        "  h+='</div>';\n"
        "  h+='<div class=\"quiz-controls__row\">';\n"
        "  h+='<span class=\"quiz-controls__label\">Filter</span>';\n"
        "  const _trapCount=G.QZ.filter((_,i)=>isExamTrap(i)).length;\n"
        "  const _aiCount=G.QZ.filter(qq=>qq.t==='AI-Ch').length;\n"
        "  const _yearSel=Array.isArray(G.years)?G.years:[];\n"
        "  const _inYearMode=G.filt==='years'&&_yearSel.length>0;\n"
        "  const _aiHardGCount=G.QZ.filter(qq=>qq.t==='AI-Hard-G').length;\n"
        "  const _aiHardAfpCount=G.QZ.filter(qq=>qq.t==='AI-Hard-AFP').length;\n"
        "  const filts=[\n"
        "    ['all',`All (${G.QZ.length})`],\n"
        "    ['2020','2020'],['2021-Jun','Jun 21'],['2022-Jun','Jun 22'],['2023-Jun','Jun 23'],\n"
        "    ['2024-May','May 24'],['2024-Sep','Sep 24'],['2025-Jun','Jun 25'],\n"
        "    ['AI-Ch',`AI (${_aiCount})`],\n"
        "    ['AI-Hard-G',`Hard-G (${_aiHardGCount})`],\n"
        "    ['AI-Hard-AFP',`Hard-AFP (${_aiHardAfpCount})`],\n"
        "    ['hard','Hard'],['slow','Slow'],['weak','Weak'],['due','Due'],\n"
        "    ['traps',`Traps (${_trapCount})`],['nbs','Next best step']\n"
        "  ];\n"
        "  const _weakForPill=getWeakTopics(3);\n"
        "  if(_weakForPill.length&&_weakForPill[0].pct!==null&&_weakForPill[0].pct<65)filts.push(['rescue','Rescue']);\n"
        "  if(dueN>0)filts.push(['due',`Due (${dueN})`]);\n"
        "  const _wrongCount=getWrongAnswerCount();\n"
        "  if(_wrongCount>0)filts.push(['wrong-review',`Review wrong (${_wrongCount})`]);\n"
        "  filts.forEach(([f,l])=>{\n"
        "    if(f==='rescue'){\n"
        "      h+=`<span class=\"pill\" data-state=\"${G.filt==='rescue'?'on':''}\" data-action=\"filter-rescue\">${sanitize(l)}</span>`;\n"
        "    } else if(f==='wrong-review'){\n"
        "      h+=`<span class=\"pill\" data-state=\"${G.filt==='wrong-review'?'on':''}\" data-action=\"filter-wrong-review\">${sanitize(l)}</span>`;\n"
        "    } else if(f==='nbs'){\n"
        "      h+=`<span class=\"pill\" data-state=\"${G.filt==='nbs'?'on':''}\" data-action=\"filter-nbs\">${sanitize(l)}</span>`;\n"
        "    } else if(EXAM_YEARS.includes(f)){\n"
        "      const _yOn=_yearSel.includes(f);\n"
        "      h+=`<span class=\"pill\" data-state=\"${_yOn?'on':''}\" data-action=\"filter-year\" data-f=\"${f}\" title=\"Click to toggle — multi-select allowed\">${sanitize(l)}${_yOn?' ✓':''}</span>`;\n"
        "    } else if(f==='all'){\n"
        "      h+=`<span class=\"pill\" data-state=\"${G.filt==='all'&&!_inYearMode?'on':''}\" data-action=\"filter\" data-f=\"${f}\">${sanitize(l)}</span>`;\n"
        "    } else {\n"
        "      h+=`<span class=\"pill\" data-state=\"${G.filt===f&&G.filt!=='topic'?'on':''}\" data-action=\"filter\" data-f=\"${f}\">${sanitize(l)}</span>`;\n"
        "    }\n"
        "  });\n"
        "  if(_yearSel.length>=2){\n"
        "    h+=`<span class=\"pill\" data-action=\"filter-year-clear\" title=\"Clear exam year filter\">Clear ${_yearSel.length} years</span>`;\n"
        "  }\n"
        "  h+='</div>';\n"
        "  h+='<div class=\"quiz-controls__row\">';\n"
        "  h+='<span class=\"quiz-controls__label\">Topic</span>';\n"
        "  h+=`<select class=\"quiz-controls__select\" data-action=\"topic-select\" aria-label=\"Filter by topic\">`;\n"
        "  h+=`<option value=\"-1\"${G.filt!=='topic'?' selected':''}>All topics</option>`;\n"
        "  TOPICS.forEach((t,i)=>{ h+=`<option value=\"${i}\"${G.filt==='topic'&&G.topicFilt===i?' selected':''}>${sanitize(t)}</option>`; });\n"
        "  h+='</select>';\n"
        "  if(G.filt==='topic'&&G.topicFilt>=0){\n"
        "    const _tqCount=G.QZ.filter(qq=>qq.ti===G.topicFilt).length;\n"
        "    h+=`<button class=\"btn btn--secondary\" data-action=\"start-mini-exam\" data-ti=\"${G.topicFilt}\" aria-label=\"Start topic mini-exam\">Mini exam (${Math.min(_tqCount,20)})</button>`;\n"
        "  }\n"
        "  h+='</div>';\n"
        "  h+='<div class=\"quiz-controls__row\">';\n"
        "  h+='<span class=\"quiz-controls__label\">Drill</span>';\n"
        "  h+=`<label class=\"btn btn--ghost\"><input type=\"checkbox\" ${G.blindRecall?'checked':''} data-action=\"toggle-blind\"> Cover options</label>`;\n"
        "  h+=`<label class=\"btn btn--ghost\"><input type=\"checkbox\" ${G.timedMode?'checked':''} data-action=\"toggle-timed\"> Timed (90s)</label>`;\n"
        "  h+='</div>';\n"
        "  if(G.filt==='wrong-review'){\n"
        "    const _wrCount=getWrongAnswerCount();\n"
        "    h+=`<div class=\"quiz-controls__row\">`+\n"
        "       `<span class=\"pill pill--danger\">Wrong-review mode · ${_wrCount}</span>`+\n"
        "       `<button class=\"btn btn--ghost\" data-action=\"wrong-review-clear\">Clear</button>`+\n"
        "       `</div>`;\n"
        "  }\n"
        "  h+='</nav>';\n"
        "  return h;\n"
        "}\n"
    )
    new_src = new_src.replace(
        "export function renderQuiz(){",
        helper + "\nexport function renderQuiz(){",
        1,
    )
    target.write_text(new_src, encoding="utf-8")

print("OK: rewrote renderQuiz() main path + added renderQuizControls() helper.")
